### ISSUE TITLE
REPL fails without fetch API

### ISSUE THREAD

**Issue by willglynn** [sveltejs/svelte.technology#10]
The REPL depends on [`fetch`](https://fetch.spec.whatwg.org), an API for which "Can I use" [reports 62.34% global availability](http://caniuse.com/#search=fetch). Support is better on desktop than on mobile, but in particular, `fetch` is not currently available in stable versions of Safari ([WebKit #151937](https://bugs.webkit.org/show_bug.cgi?id=151937)) on desktop or mobile.

There is an [XHR-based `fetch` polyfill](https://github.com/github/fetch) available.

**Comment by sterpe** [comment]
Ah, wondering why REPL wasn't working.  Ok.

**Comment by thetalecrafter** [comment]
As of e3221e33, this is working for me. Can you verify?

**Comment by willglynn** [comment]
Is this on the web? The [live REPL](https://svelte.technology/repl) currently shows Safari:

> Svelte generates components that work in all modern JavaScript environments, but the Svelte compiler only runs in Node 6+ and browsers that support ES2015 features. Please reopen this page in a different browser such as Chrome.

**Comment by thetalecrafter** [comment]
I'm able to use the REPL on Safari (10.0.2) are you using an older version of Safari?

**Comment by willglynn** [comment]
A-ha! This machine is running Mac OS X 10.11.6/Safari version 9.1.2 (11601.7.7).

**Comment by Rich-Harris** [comment]
Ah, yes — we can close this issue. There's a separate one on the main repo (https://github.com/sveltejs/svelte/issues/109) about getting the compiler to work in older environments
