### ISSUE TITLE
Prevent auto-instantiation of components with `oncreate`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#103]
Because components are currently recompiled and reinstantiated on each keystroke, work that happens in an `oncreate` handler happens over and over again, which can be a little annoying in some cases (e.g. if you're doing a `fetch`, and it keeps making requests for non-existent resources because you're in the middle of typing the URL).

One way we could prevent that is by waiting for user input before instantiating components — e.g. expecting a Cmd-Enter or a button click.

The same is true for e.g. [media elements](https://svelte.technology/repl?version=1.22.2&example=binding-media-elements).

Easiest thing to do is probably to have an option that lets you choose between as-you-type and on-command instantiation. One step beyond that would be to automatically choose between the two based on whether there's an `oncreate` or a media element (or any other similar conditions?). That would require that we have access to the component's AST, which would presumably mean updating `svelte.compile` to return a `{code, map, ast}` object instead of just `code` and `map`.

**Comment by Rich-Harris** [comment]
Oh, and `import` declarations

**Comment by Ryuno-Ki** [comment]
Have you considered [throttling or debouncing it](https://css-tricks.com/the-difference-between-throttling-and-debouncing/)?

**Comment by Ryuno-Ki** [comment]
Interesting to learn, that it can be turned into an attack in some implementations: https://blog.0day.rocks/practical-waterholing-through-dns-typosquatting-e252e6a2f99e

**Comment by Rich-Harris** [comment]
This has been implemented crudely for some time, and less crudely now that we have `stats` https://github.com/sveltejs/svelte/pull/1299
