### ISSUE TITLE
Scrolling issue on mobile

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#105]
Reproduction: visit https://svelte.technology/guide on mobile, scroll down to the section on helpers, tap 'open in REPL'. The preview is out of view

**Comment by kordeviant** [comment]
no it is not

**Comment by Rich-Harris** [comment]
What device are you on @kordeviant? Might be an Android thing

**Comment by Rich-Harris** [comment]
This seems to work fine currently, not sure what the issue was. Closing
