### ISSUE TITLE
Document `setup(component)` hook

### ISSUE THREAD

**Issue by dinoboff** [sveltejs/svelte.technology#118]
Added with sveltejs/svelte#752.

Should it be documented as a [lifecycle hook](https://github.com/sveltejs/svelte.technology/blob/master/guide/04-behaviour.md#lifecycle-hooks), with [custom methods](https://github.com/sveltejs/svelte.technology/blob/master/guide/04-behaviour.md#custom-methods) or have it's section?

**Comment by Rich-Harris** [comment]
I think it should have its own section — I've raised #119. Thanks for the prod, I'm bad at keeping the docs up to date 😬
