### ISSUE TITLE
Phrasing: "obesity crisis" / "stupid fast"

### ISSUE THREAD

**Issue by wavebeem** [sveltejs/svelte.technology#13]
There's certainly more positive ways this framework could be described:

### "obesity crisis" ➡️ 

- "JavaScript bloat"
- "size bloat"
- "size issue"

### "stupid fast" ➡️ 

- "super fast"
- "lightning fast"
- "super quick"

**Comment by therealnicksaunders** [comment]
http://www.urbandictionary.com/define.php?term=stupid%20fast

https://www.washingtonpost.com/opinions/why-we-cant-get-our-obesity-crisis-under-control/2015/12/25/8899d4ec-a8f0-11e5-8058-480b572b4aae_story.html?utm_term=.5402b707512a

**Comment by proyb6** [comment]
@wavebeem I must say, the Svelte's original heading is an eye catching attention for developers and non-IT user (it's good for presentation that also mentioned in scientific article).
