### ISSUE TITLE
Mention REPL .zips in guide

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/svelte.technology#134]
Getting started by using the 'download zip' feature in the REPL is mentioned in the second blog post, but that's not very visible. The 'getting started' part of the guide mostly talks about `svelte-cli` which, while it does make the point of there being no large runtime script to include, is arguably not the best way for someone to play around with Svelte.

I don't think `svelte-cli` should be completely removed from the 'getting started' section, but I do think people should be encouraged to use the starter project. Maybe there could even be a 'download .zip' button next to the 'open in REPL' links in the guide, but I'm not sure how straightforward that would be.

**Comment by Rich-Harris** [comment]
Yeah, that's a good point. Maybe we could link out to https://svelte.technology/blog/the-easiest-way-to-get-started as well
