### ISSUE TITLE
Use ES5 in <script> blocks

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#14]
Otherwise it's a bit confusing – Svelte generates code that doesn't need a transpiler, and the use of ES2015 in the code samples signals otherwise

**Comment by sterpe** [comment]
+1 Also the note was a bit confusing since it reads:
```
While Svelte will generate ES5 code that runs everywhere, it won't convert your ES2015 code into ES5 – so if you use ES2015 and need to support older browsers, you will need an additional transpilation step in your build process using Babel or Bublé.
```
I'm thinking you mean it won't transpile the code in the script tags...but it seems like a weird construct: It generates ES5 but won't convert your code ...like huh?  ;)

**Comment by Rich-Harris** [comment]
Decided to use ES2015 in the end — it's 2018 now, it's well supported and well known, and it makes the sample code a lot more compact
