### ISSUE TITLE
Shorthand for bind:attribute missing from docs

### ISSUE THREAD

**Issue by louwers** [sveltejs/svelte.technology#140]
The docs write:

> If the attribute and the bound property share a name, you can use this shorthand:
> ```js
> <CategoryChooser bind:category/>
> ```

But in this case an even shorter version can be used if I am not mistaken:

```js
<CategoryChooser :category/>
```

This shorthand is not mentioned in the docs.

**Comment by Rich-Harris** [comment]
`:category` isn't actually a shorthand for `bind:category`, it's a shorthand for `category={{category}}`. You're right, we do need to document that!
