### ISSUE TITLE
Small error in {{elseif ...}} example

### ISSUE THREAD

**Issue by larister** [sveltejs/svelte.technology#15]
In the [elseif](https://svelte.technology/guide#if-blocks) example, we have the following:

```
{{elseif 5 > x}}
  <p>{{x}} is less than 5</p>
```

It should be `5 < x`; I tried fixing this myself but couldn't figure out how to tell codemirror _not_ to treat this as the start of a closing tag...

**Comment by proyb6** [comment]
@larister 
```
if x is 4
5 > 4 
4 is less than 5
```

**Comment by Rich-Harris** [comment]
@proyb6 is correct 😀 The condition is `5 > x` which is equivalent to `x < 5` (but yep, the tag thing), which matches the sentence `{{x}} is less than 5`

**Comment by larister** [comment]
I feel silly; I always write `x > {condition}` and my brain did the flip without me noticing. Thanks both.
