### ISSUE TITLE
Show error if JSON is invalid

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#156]
Via https://github.com/sveltejs/svelte/issues/938 — if a gist contains invalid JSON, the REPL doesn't appear to mind: https://svelte.technology/repl?version=1.42.0&gist=2afe785004bcdc4c1bcca6f03f2ed7f9

It should show an error instead.

**Comment by emirotin** [comment]
The error is shown as I see now, but it's subtle and hard to decipher. 
Generally there are 2 or 3 different places where errors are shown, and sometimes it's top of the panel, sometimes as in this case it's at the bottom.

**Comment by emirotin** [comment]
I can send a PR that would use https://github.com/json5/json5 instead of vanilla JSON.parse for parsing the `json` field into `data`. That will effectively allow writing in the data panel in the same way one would do in normal JS code.

**Comment by Rich-Harris** [comment]
I agree that this would be better. One thing that concerned me a bit about using JSON5 is that it would be somewhat jarring when the *component* updates the data, because it would have to stringify the current state in a way that is unlikely to match the user's formatting.

So I whipped up a little module that makes it possible to update the string in place: https://github.com/Rich-Harris/golden-fleece

The idea is that you take a JSON5 string, throw a new object at it, and it will 'patch' the string to add the new values non-destructively. (It isn't at all battle-tested yet!) 

A PR would be awesome if you have time! Thank you 😀

**Comment by emirotin** [comment]
Heh, nice module. Will try to find time early this (coming) week.
Though IMO having a prettier-like experience with reformat-on-blur would be OK too.

**Comment by Rich-Harris** [comment]
this is now implemented
