### ISSUE TITLE
Document `data` override in options passed to a component a bit better

### ISSUE THREAD

**Issue by bradstaff** [sveltejs/svelte.technology#157]
I know this is touched on a little bit in [behaviours for default data](https://svelte.technology/guide#default-data)

> Data supplied at instantiation (i.e. new Component(...)) takes priority over defaults.

but what _isn't_ clear is the fact that the object key, `data` passed in to a component as an option __becomes__ the data. I was running into this problem where I'm programmatically passing in the component I want to instantiate to a child component: e.g.

`Parent.html`
```html
<div>
    <h1>{{name}}</h1>
    <div class="{{css.collective}}" ref:mount>
    </div>
</div>

<script>
    import Instance from "./instance.html";

    export default {
        
        oncreate() {
            opts.cases.forEach((c) => (
                new Instance({
                    target: this.refs.mount,
                    component: Instance,
                    data: { css: { ...styling data }, count: 3, title: "hello" } 
                })
            );
        },

        components : { Instance }
    };
</script>
```

`Instance.html`
```html
<div class="{{css.whatever}}">
    <h2> {{title}} </h2>
    <div ref:mount />
</div>

<script>
    export default {
        oncreate() {
            const Component = this.options.component; 

            new Component({ 
                target  : this.refs.mount,
            });
        }, 
    }
</script>
```

__What wasn't clear to me__: If I pass some arbitrary data under the key of `data` into a child component, that becomes the assumed state of the child component and is ready to use in templates e.g.

`data: { css: {...}, title: "..." }` can be referenced in the HTML template as `{{css.whatever}}` and `{{title}}` with no additional configuration. 

If default data doesn't exist in `Instance`, I can still access it normally in the html template as if it were, _as long as it's supplied as `data: { ... }`_ from the parent component. Essentially `this.options.data` == `this.get()`

I actually tried this anti-pattern to set data because I was running into undefined errors with my css object:

```js
{
    oncreate() {
        const Component = this.options.component
        
        
        this.set("css", this.options.data.css);
        this.set("title", this.options.data.title); 
    }
}
```

I was wondering why I was running into this issue where using `{{css.whatever}}` in my template would throw errors, because I set it. but it turns out the shape of `data` was something I didn't assume to take over the state of the component.

This is a long post for probably an easy sentence restructuring or addition, so I'll probably submit a PR over the holiday for it.

**Comment by Rich-Harris** [comment]
How about [this](https://github.com/sveltejs/svelte.technology/blob/69afed47e1ae543adac142145b037b6c8f416feb/content/guide/04-behaviour.md#default-data)?

**Comment by bradstaff** [comment]
Rich you're a MACHINE. 

This looks great. I think the biggest disconnect I had was that `data: { prop: ... }` was accessible as `{{prop}}` in the template when passed in via a parent context. 

Feel free to close this once it's merged!
