### ISSUE TITLE
Document `Store`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#159]

**Comment by zigomir** [comment]
I had to open chrome dev tools and hit `Clear site data` under `Application` tab to get new docs about the store...probably due to service worker. Maybe it was already fixed in meantime, because I believe I was quite early on visiting svelte.technology/guide.

**Comment by dschulten** [comment]
On Chrome mobile: Settings-Site Settings-Storage-svelte.technology-Clear and reset

**Comment by Rich-Harris** [comment]
This *should* be fixed now, following #164 — the next time you visit the site, it should load the correct service worker which will kill the old one.
