### ISSUE TITLE
REPL fails to load

### ISSUE THREAD

**Issue by johnmuhl** [sveltejs/svelte.technology#181]
Very recently the online REPL stopped loading.

~~~
Linux 4.13.16-202.fc26.x86_64 #1 SMP Thu Nov 30 15:39:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
~~~
~~~
Google Chrome version 63.0.3239.108 (Official Build) (64-bit)
~~~

Same happens with the latest Firefox.

![image](https://user-images.githubusercontent.com/7944/34268615-08062c36-e647-11e7-8c0b-8b01335b8bea.png)

**Comment by Rich-Harris** [comment]
Thanks — looking into it. Looks like this is a bug with the most recent version of Sapper, it's not streaming the full contents of the page to the client

**Comment by Rich-Harris** [comment]
Aaaaaand we're back! Thanks again. We need to add some acceptance tests on this thing
