### ISSUE TITLE
Document {{yield}}

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#19]

**Comment by Crisfole** [comment]
Happy to write a first pass for you. Can I assume this works identically to how Ractive works?

**Comment by Rich-Harris** [comment]
Hey @Crisfole — sorry, I didn't see your offer but it's much appreciated! Have added a section on yield: https://svelte.technology/guide#yield-tags. It's brief but hopefully does the job. Yeah, it works identically to Ractive's, except that we don't yet have named yields
