### ISSUE TITLE
Open in REPL links all go to https://svelte.technology/repl/?gist=0ed5146aa22c28410dfcff2050f3d2f8

### ISSUE THREAD

**Issue by rmacklin** [sveltejs/svelte.technology#2]
Came across this (sounds really interesting by the way!) and was looking through the guide, but I'm seeing a strange behavior where each code block's "Open in REPL" link seems to take me to the same `Hello {{name}}` example at https://svelte.technology/repl/?gist=0ed5146aa22c28410dfcff2050f3d2f8

The links themselves are distinct prior to the redirect though, e.g. `https://svelte.technology/repl/?shareable=JTdCJTIyZ2lzdCUyMiUzQW51bGwlMkMlMjJzb3VyY2UlMjIlM0ElMjIlM0NwJTNFJTdCJTdCYSU3RCU3RCUyMCUyQiUyMCU3QiU3QmIlN0QlN0QlMjAlM0QlMjAlN0IlN0JhJTIwJTJCJTIwYiU3RCU3RCUzQyUyRnAlM0UlNUNuJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMmElMjIlM0ExJTJDJTIyYiUyMiUzQTIlN0QlN0Q=` and
`https://svelte.technology/repl/?shareable=JTdCJTIyZ2lzdCUyMiUzQW51bGwlMkMlMjJzb3VyY2UlMjIlM0ElMjIlM0NoMSUyMHN0eWxlJTNEJ2NvbG9yJTNBJTIwJTdCJTdCY29sb3IlN0QlN0QlM0InJTNFJTdCJTdCY29sb3IlN0QlN0QlM0MlMkZoMSUzRSU1Q24lMjIlMkMlMjJkYXRhJTIyJTNBJTdCJTIyY29sb3IlMjIlM0ElMjJzdGVlbGJsdWUlMjIlN0QlN0Q=`.

I'll come back to this later tonight and see if I can fix this issue (if you haven't already fixed it yourself).

**Comment by Rich-Harris** [comment]
Ah, dammit! Thanks – initially all the links worked that way, but when I deployed the app it broke with some components because the URL got too long. Fixing it now

**Comment by Rich-Harris** [comment]
Fixed 👍

**Comment by rmacklin** [comment]
Thanks! I think that change may have caused another breakage though: https://github.com/sveltejs/svelte.technology/commit/b1d7da9461889e707bb98edb262350760bdeb4ff#commitcomment-20009844

**Comment by Rich-Harris** [comment]
@rmacklin oh lord, I'm an idiot. Thanks for noticing – have just pushed a fix, should get redeployed momentarily
