### ISSUE TITLE
fix gist API fallback

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#205]
looks like I broke this during the Sapper rewrite

**Comment by Conduitry** [comment]
Possibly all this needs is a change to https://github.com/sveltejs/svelte.technology/blob/master/routes/api/gists/[id].js to add

```javascript
let credentials = {
	id: process.env.client_id,
	secret: process.env.client_secret
};
```

**Comment by Rich-Harris** [comment]
I suspect that was the correct diagnosis, though it's rendered moot by #224 — will close this
