### ISSUE TITLE
Svg examples not working

### ISSUE THREAD

**Issue by mhkeller** [sveltejs/svelte.technology#216]
In FF 58.0.2 and Chrome 65.0.3325.146 get the error ` setting getter-only property "className"`: 

FF
<img width="1280" alt="screen shot 2018-03-10 at 4 54 59 pm" src="https://user-images.githubusercontent.com/498744/37247091-fa363ab2-2483-11e8-81a7-82dee9fce4b9.png">

Chrome
<img width="1280" alt="screen shot 2018-03-10 at 4 59 14 pm" src="https://user-images.githubusercontent.com/498744/37247126-687ea19e-2484-11e8-9168-e25d00d2e15b.png">

**Comment by Conduitry** [comment]
Thanks! This is an issue in Svelte itself, not the website or the examples (if you edit the URL to run the example on Svelte 1.56.4 or earlier, it works) - so I'm closing this in favor of https://github.com/sveltejs/svelte/issues/1224

**Comment by Rich-Harris** [comment]
Fixed in 1.57.2 https://svelte.technology/repl?version=1.57.2&example=svg-clock
