### ISSUE TITLE
The repl is so awesome it deserves its own repo

### ISSUE THREAD

**Issue by burningTyger** [sveltejs/svelte.technology#235]
The repl is a fantastic editor for quickly getting a component ready. At least I would love to incorporate it into my app so that my users can create components for their very own purposes. Maybe others would love to do the same? Widgets or some other components could be live edited.
Would it be very hard to get it into its own repo so that it can be used elsewhere? Instead of hardcoding everything into it a simple config file would be a great addition so that instead of gists on github other sources could be used to share components.

**Comment by arxpoetica** [comment]
This is teh awesome.

**Comment by burningTyger** [comment]
I just happened. Thank you.
