### ISSUE TITLE
Replace `repl?data=...` URLs with gists

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#239]
The URLs aren't shareable, because the query is too long. It would be better if they were gists in their own right

**Comment by Conduitry** [comment]
Hrm. I'd really prefer it if, whatever solution is used for this, it didn't make it more complicated to just have examples in the markdown files in the docs that render as code blocks with 'open in repl' links. I don't currently see a practical way to do that.

(And tbh, while we're on the subject, I'm not totally comfortable with the built-in repl examples living in gists, although I'm finding it difficult to articulate why exactly.)

**Comment by Conduitry** [comment]
Yeah something with guide examples stored on the server and accessed via another endpoint by hash is about what I was thinking. It could also work with the REPL examples of course. (The parsing might be different, but the hashing and the endpoint could be the same.)
