### ISSUE TITLE
REPL: data changes aren't getting saved correctly (returns 422)

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/svelte.technology#241]
When I change data in the REPL, for example `{}` or `{"foo":"gar"}` and then try to save, it's sending back an `Invalid request` `422` error. (I think from `gist.github`?).

Here's what the response looks like:

```
{
  "message": "Invalid request.\n\nFor 'additionalProperties', \"{\\\"foo\\\":\\\"gar\\\"}\" is not an object or null.",
  "documentation_url": "https://developer.github.com/v3/gists/#edit-a-gist"
}
```

![image](https://user-images.githubusercontent.com/111424/38067314-16fc32da-3336-11e8-96b2-ee16bda22936.png)

**Comment by burningTyger** [comment]
When I last checked a couple hours ago save worked again for me. But I noticed this behaviour too. Maybe  just a temporary issue on github's side?

**Comment by arxpoetica** [comment]
It's still happening for me. Note, it only seems to happen on second time saving. Agree though that it could be a GitHub thing, but it doesn't seem likely.

**Comment by Conduitry** [comment]
Nope not a github thing, this was a bug on our end. Created PR #242
