### ISSUE TITLE
Error loading svelte/store from bundle.run

### ISSUE THREAD

**Issue by btakita** [sveltejs/svelte.technology#245]
Seems like importing `svelte/store` is throwing an error.

https://svelte.technology/repl?version=1.59.0&gist=6d6e54f5e05e055834c37b62eca8199d

**Comment by Conduitry** [comment]
That REPL link is for the default nested component example, with no store stuff. I just tried to use the store and it worked fine - https://svelte.technology/repl?version=1.59.0&gist=25efac5b11a0710f638ac99684519f46
