### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#266]
This error sometimes flashes up when loading the REPL — some race condition that isn't being handled

**Comment by Rich-Harris** [comment]
haven't seen this in a while, will be optimistic and assume it's fixed

**Comment by daison12006013** [comment]
For someone who ever visited this issue, try to check your code if there are null returned inside elements

e.g:
```
<img class="{isRounded ? 'rounded-full' : null}" />
```

Instead of returning null, you should return an empty string.
