### ISSUE TITLE
Allow to use css precompilers for component style

### ISSUE THREAD

**Issue by dschulten** [sveltejs/svelte.technology#27]
For a use case why that might make sense, consider a responsive menu like https://gist.github.com/lavoiesl/7664315.

Is this something a plugin could solve?

**Comment by dschulten** [comment]
I have found the pointer to compiler plugins at https://github.com/sveltejs/svelte/issues/194. Renamed title ;-)

**Comment by Rich-Harris** [comment]
I'll close this as it's being tracked at https://github.com/sveltejs/svelte/issues/181
