### ISSUE TITLE
Docs should advise this.observe("$foo") over this.store.observe("foo") in oncreate handlers

### ISSUE THREAD

**Issue by PikadudeNo1** [sveltejs/svelte.technology#272]
According to sveltejs/svelte#1181, only observers of the former form will be destroyed if the component is destroyed, yet the docs tell people to use the latter form in [this section](https://svelte.technology/guide#accessing-the-store-inside-components), and don't document the former anywhere. This could direct developers to shoot themselves in the foot and write memory-leaking apps.

**Comment by Rich-Harris** [comment]
Thanks — I went the other way, documenting that the listener should be removed, as listening for `$foo` has caveats (the component will only receive those changes if `$foo` is referenced in the template or in a computed property)
