### ISSUE TITLE
Need document for v1

### ISSUE THREAD

**Issue by szmtcjm** [sveltejs/svelte.technology#281]
I find that the svelte.technology website is on v2. 
But I need document for v1...

**Comment by furstenberg** [comment]
You could check out an earlier commit from the repo perhaps? From the v1 days.

**Comment by Rich-Harris** [comment]
Yep, afraid that's the only way — we don't have the resources to maintain docs for old versions (we barely get by keeping them current!). I'd strongly recommend upgrading to v2, as there won't be any further bugfixes or performance updates for v1. It's a fairly straightforward migration: https://svelte.technology/blog/version-2

**Comment by ugultopu** [comment]
Which repository would that be? No docs seem to exist under [sveltejs/svelte v1](https://github.com/sveltejs/svelte/tree/v1.0.0).

**Comment by Conduitry** [comment]
As far as I can tell, the latest v1 docs live at https://github.com/sveltejs/v2.svelte.dev/tree/f3ead018a59b967f73e0083680d859d3a0153b96

**Comment by ugultopu** [comment]
@Conduitry Thank you. Two questions:
- How did you figure out the commit hash? [v2.svelte.dev](https://github.com/sveltejs/v2.svelte.dev) doesn't have any tags.
- The commit that you linked is made at 2018-04-16, wheres Svelte v1 (that I linked above) is made at 2016-11-29. So, I'm confused how that can be the docs for v1.
