### ISSUE TITLE
Should REPL remove added <style> tags from the iframe before inserting a new example?

### ISSUE THREAD

**Issue by rmacklin** [sveltejs/svelte.technology#3]
I was looking at the Scoped Styles example when I noticed this (focus on the DOM inspector):

![multiplestyletags](https://cloud.githubusercontent.com/assets/1863540/20739996/834f2ba8-b674-11e6-80eb-36d9603f353c.gif)
[(Click to enlarge)](https://cloud.githubusercontent.com/assets/1863540/20739996/834f2ba8-b674-11e6-80eb-36d9603f353c.gif)

It seems that the `<style>` tag that gets inserted into the REPL's iframe does not get removed when you switch examples, and if you revisit the Scoped Styles example a duplicate `<style>` tag will be inserted (each time you revisit it). Since the styles are the same, there isn't really any harm done, but I figured I'd mention it because it seems unintentional - svelte by itself has [the `addedCss` variable](https://github.com/sveltejs/svelte/blob/370db7d2691b9f19eed5cb53a5448f21b851dea4/compiler/generate/css/process.js#L9) which seems [to prevent the styles from being added multiple times](https://github.com/sveltejs/svelte/blob/36a4befc3e13589ccb7bbdddb4d9429e585f8b9e/compiler/generate/index.js#L337); however, I think the iframe is getting a new `addedCss` every time you change the example.

Like I said, this might not need fixing at all, which is why I phrased the issue title as a question...

**Comment by Rich-Harris** [comment]
Whoops! You are entirely correct, this is unintentional. Fixed by bb36ecea057c62ac3505afae095a485eab8b255b – thanks
