### ISSUE TITLE
Corrupted Content Error

### ISSUE THREAD

**Issue by gka** [sveltejs/svelte.technology#302]
every once in a while I can't load the svelte website because of a "corruted content error". this has happened for quite a while now but usually it goes away after a while. ideally this would never happen.

![image](https://user-images.githubusercontent.com/617518/40650185-f48ad760-6332-11e8-883e-62386ea02286.png)

Firefox Quantum 60.0.1 (64-bit) (Ubuntu)

**Comment by Conduitry** [comment]
I have occasional DNS resolution issues with svelte.technology (and other sites using now.sh) but I've never seen a corrupted content error. Really not sure what could be causing this besides Now or other network weirdness.
