### ISSUE TITLE
REPL being revamped?

### ISSUE THREAD

**Issue by tomByrer** [sveltejs/svelte.technology#318]
I"m finding quite a few errors in the examples, JSON data is wrong, version, [old Svelte is being used](https://svelte.technology/repl?demo=binding-input-checkbox-group) (need double `{{}}`), etc.

Want PRs, or are you in the middle of documentation v2? revamp?

**Comment by Rich-Harris** [comment]
The right version of Svelte is being used in that link, no? (It'll use whatever version you specify in the `?version=` part of the URL.)

There have been a few changes to the REPL recently though, yeah — any specific errors you can point to? Thanks

**Comment by tomByrer** [comment]
>  (It'll use whatever version you specify in the ?version= part of the URL.)

Ah, ty, that's the error!

I'm not sure if specifying Svelte versions in URL is a good idea when the demo code can change without warning.  So changes in the API can break old bookmarks:
https://github.com/flagello/awesome-sveltejs/pull/10

Maybe the demo code should be versioned also?  I like [CodeSandbox.io](https://codesandbox.io/search?query=svelete), but understand REPL loads a bit faster.

Closing since the bookmark-impact is low, but may become an issue later as Svelte gains popularity & v3 breaks more old demos.
