### ISSUE TITLE
Make REPL mobile-friendly

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#34]
Via [Twitter](https://twitter.com/rossipedia/status/835307969160032256). It's a bit of a tricky problem — a REPL is never going to be a great experience on mobile — but we can probably do better than the status quo

**Comment by rossipedia** [comment]
I'm not super interested in editing things and having the full REPL experience, but to just be able to read the code and see some output would be nice.

I might try my hand at making the font a little smaller and turning it read-only

**Comment by Ryuno-Ki** [comment]
![tmp_20602-screenshot_2017-02-25-19-13-12-90839088](https://cloud.githubusercontent.com/assets/3097194/23333618/7a5fd7ea-fb8e-11e6-895b-d6399dad2b63.png)

My fairphone can't be used for REPL o.O
Plus, note the collisions between logo and navigation.

**Comment by Rich-Harris** [comment]
The REPL now appears on mobile — closing this
