### ISSUE TITLE
Markdown fails to render inside lists

### ISSUE THREAD

**Issue by KellerFuchs** [sveltejs/svelte.technology#363]
See <https://svelte.technology/blog/version-2#tl-dr> for example.  Reproduced with JS enabled or not.

**Comment by Conduitry** [comment]
Looks like there's also an issue that appeared sometime with some other processing on that page. "If you need to show an actual `{` character, it's as easy as `{`" Very helpful! 😬

**Comment by KellerFuchs** [comment]
Thanks!  Foxes rule!
