### ISSUE TITLE
Feature Suggestion: Allow html entities in <svelte:head>

### ISSUE THREAD

**Issue by matt3224** [sveltejs/svelte.technology#367]
Good day,

I have a use case where my title tag is populated with a title pulled from WordPress, sometimes this has a html entity in it and instead of getting a title like "This & That" i'll get "This &#038; That".

I see that i'm unable to use @html since I imagine `document` isn't available. My work around is to do some regex foo to convert it.

```js
const htmlToStr = (str) => {

    return str.replace(/&#([0-9]{1,3});/gi, function(match, numStr) {

        const num = parseInt(numStr, 10); // read num as normal number

        return String.fromCharCode(num);
    });
}
```

Could we do anything to allow html entities auto-magically in `<svelte:head>`?

**Comment by MaxMilton** [comment]
Wrong repo, this is for the <https://svelte.technology> website. You'll probably want to open an issue in <https://github.com/sveltejs/svelte> instead.
