### ISSUE TITLE
Add a list of companies or organisations using Svelte

### ISSUE THREAD

**Issue by mindrones** [sveltejs/svelte.technology#379]
Following a quick on conversation in the chat, I'm opening this issue to start listing companies/orgs using Svelte.

It would be ideal to collect name and SVG logo.

<details>

Since we can't upload svg files, we can:

- change extension of the SVG file to .txt

- upload the txt file in the comment, getting something like:
```
[mylogo_svg.txt](https://github.com/sveltejs/svelte.technology/files/12345/mylogo_svg.txt)
```
- eventually upload a png/jpg corresponding to that svg and link it to the txt file like this: 
```
[![mylogo_image_name](https://user-images.githubusercontent.com/nnnnn/hash.png)](https://github.com/sveltejs/svelte.technology/files/nnnnn/mylogo_svg.txt)
```
</details>

**Comment by mindrones** [comment]
+ Nesta: http://www.nesta.org.uk (atm we have .png and .jpg logos, I'll upload the SVG logo as soon as possible)

**Comment by Rich-Harris** [comment]
![NYT](https://upload.wikimedia.org/wikipedia/commons/5/58/NewYorkTimes.svg)

**Comment by antony** [comment]
Beyonk: https://beyonk.com - written in Svelte and Sapper.

![logo](https://user-images.githubusercontent.com/218949/48921814-42545f00-ee9a-11e8-8bd6-25975d4e4dae.png)

**Comment by morleytatro** [comment]
https://phonesnag.com - Svelte SSR with pagejs for routing

**Comment by saibotsivad** [comment]
[From Now On](https://from-now-on.com/): The webapp used to manage app content is built with Svelte as an SPA. We're still on 1 😬 

![logo](https://static1.squarespace.com/static/55d227d8e4b05b3ce73a11dd/t/5aa1c18a419202b500c34631/1545415719253/?format=1500w)

**Comment by c0bra** [comment]
https://onboardist.github.io/ - No real logo to speak of.

**Comment by kaisermann** [comment]
[Stone Payments](https://github.com/stone-payments/pos-mamba-sdk) :call_me_hand:

**Comment by furstenberg** [comment]
[itslearning](https://itslearning.com/) uses Svelte.

[itslearning.svg.txt](https://github.com/sveltejs/svelte.technology/files/2931728/itslearning.svg.txt)

**Comment by Ryuno-Ki** [comment]
You may find brand images on https://www.brandsoftheworld.com/logos btw

**Comment by lisacharlotterost** [comment]
[Datawrapper](https://www.datawrapper.de/) 

[![datawrapper](https://user-images.githubusercontent.com/9379282/53945316-a3a6e380-40c1-11e9-9598-41d8134d4c2d.png)](https://github.com/sveltejs/svelte.technology/files/2940358/datawrapper.txt)

**Comment by phromo** [comment]
I found svelte by opening the sources of https://distill.pub they have it in their recommended repo: https://github.com/distillpub/post--example

**Comment by PaulMaly** [comment]
[Mustlab](http://mustlab.ru) - outsource web, mobile, smart tv, iot apps from scratch.

![mustlab-logo](http://mustlab.ru/img/logo-big.png)

**Comment by cbenz** [comment]
![dbnomics-logo1](https://user-images.githubusercontent.com/12686/54703711-99f99300-4b39-11e9-9511-2652d9a60bb6.png)

[DBnomics](https://db.nomics.world) – the world's economic database

[source code](https://git.nomics.world/dbnomics/dbnomics-website/)

**Comment by termleech** [comment]
![logo](https://user-images.githubusercontent.com/479722/55033641-9e162c80-4fe1-11e9-8df6-865f809b440b.png)

chess.com - #1 online chess site

**Comment by aubergene** [comment]
Bloomberg.com/graphics we use Svelte and love it <3 I'm confirming with legal about using our logo

**Comment by Rich-Harris** [comment]
Thanks everyone — I've added all the organisations with logos, with a [+ your company?](https://github.com/sveltejs/svelte/blob/master/site/src/components/WhosUsingSvelte/index.svelte) link: https://v3.svelte.technology/

@aubergene that makes sense. Had actually been wondering about applying to the OpenJS Foundation, so if that happens I'll let you know 😀

**Comment by ghost** [comment]
Link dead. https://svelte.dev/

**Comment by nielsbosma** [comment]
We use Svelte for our new website http://filestar.com and it's absolutely amazing! We ❤️️ Svelte!

**Comment by tretapey** [comment]
https://cracss.com

**Comment by maxmilton** [comment]
@tretapey please don't post in a closed thread as it's likely to go by unnoticed. If you want to submit a new showcase website, please open an issue or PR at https://github.com/sveltejs/community

**Comment by ghost** [comment]
@nielsbosma I checked the site and wonder, why its performance score is lower than i expected. 
![Screenshot_15](https://user-images.githubusercontent.com/1254613/76501864-17f23080-6454-11ea-85d8-358f8daf9caf.png)

https://cracss.com is score is very high.
![Screenshot_16](https://user-images.githubusercontent.com/1254613/76502050-656e9d80-6454-11ea-98e7-a03646235421.png)

**Comment by Conduitry** [comment]
This isn't the place for any of these sorts of conversations.
