### ISSUE TITLE
CSP header set to self for style-src causes oncreate to fail

### ISSUE THREAD

**Issue by solox174** [sveltejs/svelte.technology#391]
When the CSP header it set to self for style-src an exception is thrown when any component is destroyed. After the exception is thrown the first time, the oncreate function stops firing for all components. They still load, but any code in oncreate does not execute. I was able to work around it by using onstate, which still fires, instead and only executing when previous is undefined but I can' t access the DOM here so it is only a partial workaround. 

The Svelte version I am using is 2.16.0.

It appears Svelte is trying to append a style element to document.head but the browser is blocking it causing an exception.  The exception is:

> Uncaught TypeError: Cannot read property 'insertRule' of null

The offending code as reported by the browser is:

>          addRule(b, M) {
>             if (!this.stylesheet) {
>                 const b = q("style");
>                 document.head.appendChild(b),
>                 y.stylesheet = b.sheet
>             }
>             this.activeRules[M] || (this.activeRules[M] = !0,
>             this.stylesheet.insertRule(`@keyframes ${M} ${b}`, this.stylesheet.cssRules.length))
>         },

**Comment by MaxMilton** [comment]
Is this related to the <https://svelte.technology> website? Perhaps it would be better to post this in the Svelte repo, <https://github.com/sveltejs/svelte>.

**Comment by solox174** [comment]
Sorry wrong page :(
