### ISSUE TITLE
Blog has no RSS feed

### ISSUE THREAD

**Issue by wezm** [sveltejs/svelte.technology#4]
Please add an RSS feed to the blog so I may subscribe and keep track of progress.

**Comment by Rich-Harris** [comment]
Here it is, at long last — https://svelte.technology/blog/rss.xml — now I just need to write some more blog posts!

**Comment by Ryuno-Ki** [comment]
@Rich-Harris I think, you broke that during a rewrite :-(

**Comment by Conduitry** [comment]
https://svelte.technology/blog/rss.xml is working for me, what are you seeing?

**Comment by Rich-Harris** [comment]
wow, that is subtle. thanks for the fix @Conduitry, redeploying

**Comment by Ryuno-Ki** [comment]
@Conduitry It triggered a download prompt in Firefox for me. Better now :-)
