### ISSUE TITLE
Props editor with zero only

### ISSUE THREAD

**Issue by bravecow** [sveltejs/svelte.technology#402]
Multiple `0` are not printed:

![image](https://user-images.githubusercontent.com/988471/53895593-0ef9a280-403b-11e9-86b7-db37a2898926.png)

**Comment by Conduitry** [comment]
This is the repo for the old/v2 site (at svelte.technology). The new v3 site which this is a screenshot of is in the main Svelte compiler repo under the site directory - https://github.com/sveltejs/svelte/tree/master/site

There are currently some known issues surrounding the props editor in the v3 site's REPL - one of which is that it doesn't display the initial value of the prop. Props can be any js expression, not just strings, so you'd need to enter this as `'00000'` or `"00000"`. (This will be more clear once the initial value `"world"` is displayed in the props editor when you load the REPL.)
