### ISSUE TITLE
Support HTML5 Touch API

### ISSUE THREAD

**Issue by raphet** [sveltejs/svelte.technology#415]
***Request*** 
Implement HTML5 Touch API support in svelte

***Reference*** 
https://caniuse.com/#feat=dragndrop

***Notes***
Drag & drop in svelte currently only works on desktops, not mobiles (e.g. android chrome):
https://github.com/sveltejs/v2.svelte.dev/issues/208

**Comment by Conduitry** [comment]
This isn't the right repo for feature requests in Svelte.

Also, it's not clear to me what implementing touch support would mean. You can already use all browser APIs in Svelte.

**Comment by raphet** [comment]
@Conduitry 
Ok, in that case I will close it here, but you can check comments and examples https://github.com/sveltejs/v2.svelte.dev/issues/208#issuecomment-497385604

Svelte v3 does not (or at least not working) support the html5 touch api.
