### ISSUE TITLE
Should REPL default to `dev: true`?

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/svelte.technology#45]
Should the REPL default to compiling with `dev: true`? Should this be provided as an togglable option in the UI?

**Comment by Conduitry** [comment]
Okay this by itself is probably not a great idea. The errors that would now be thrown while running the component aren't displayed in the UI. This should wait at least until after #39.

**Comment by Conduitry** [comment]
Since there's nice runtime error reporting in the REPL, it makes sense to revisit this.

Having dev mode on in the REPL would probably be the most helpful overall, but I'm concerned about people not even being aware of dev mode and then getting confused why the REPL's not behaving the same as the identical code locally for them. Perhaps a dev mode checkbox in the UI that defaults to enabled?

**Comment by Rich-Harris** [comment]
I reached the same conclusion. Slightly wary of button-itis, but it would also mean we could show people what `shared: true` output looks like, if we had an options interface

**Comment by Conduitry** [comment]
REPL has been using `dev: true` for a while now, so I'll close this. We can revisit buttons to control compiler options if we feel like they're needed.
