### ISSUE TITLE
Increase the font-width for the website

### ISSUE THREAD

**Issue by turbo** [sveltejs/svelte.technology#5]
Everything from the normal text bodies to the code font in the REPL is too thin to be accessible. Thin fonts are not readable to people with limited eyesight, elderly people and whoever uses Low-DPI screens with Windows.

I linked some general design guidelines here: https://news.ycombinator.com/item?id=13070021

It's your decision anyway, but at least for me, it would reduce much unneeded eyestrain. :-)

**Comment by jonboiser** [comment]
I agree, although I think what needs to be increased is the _font-weight_. Currently, the site is using Roboto Light (100 weight), whereas it might be a little more readable if it just used the regular weight and made some tweaks to point size and line height.

**Comment by turbo** [comment]
Of course, I meant to say weight. Thanks.

**Comment by Rich-Harris** [comment]
Hey – thanks for the feedback. I've bumped up the weights in a few different places, hopefully it's enough to make the site more readable.
