### ISSUE TITLE
Put examples in repo

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#51]
The save-as-gist is a nice feature, but if a bunch of people from the same large office try to access the REPL at the same time, they can quickly hit the gist API rate limit. Should probably have the default examples in this repo instead. Also adds a bit more accountability, ability to update following any changes (e.g. onrender -> oncreate), and so on.

**Comment by Conduitry** [comment]
I was a little trigger happy on my pushes, haha. I didn't realize they would all show up here 😨 Just pretend I got the code perfect the first time.

**Comment by Conduitry** [comment]
Hm, so how is that automatic deployment currently working? This has been merged into master but https://svelte.technology/repl.js is not showing my changes right now.

**Comment by Rich-Harris** [comment]
Not sure to be honest... looks like it's fixed now
