### ISSUE TITLE
prehistoric version of uglify-js

### ISSUE THREAD

**Issue by kzc** [sveltejs/svelte.technology#54]
The version of `uglify-js` in the `yarn.lock` file is quite old due to:

https://github.com/gobblejs/gobble-uglifyjs/blob/e7eacf48a44c02064a62133b9b157f2deca86455/package.json#L13

`uglify-js@2.7.5` is stable.

**Comment by Rich-Harris** [comment]
Thanks — looks like this got fixed as part of the big rewrite (#56), no Gobble any more, it uses Uglify directly. Nice to see Uglify under active development again.
