### ISSUE TITLE
Download/export button on REPL

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#73]
Something I'd really like to have, next to the 'save' button — a download button that generates a zip file with your project already set up, so that you just need to follow the instructions in the provided README (which would basically amount to '`npm install`, `npm run dev`, open localhost, start hacking'). Would make for a really nice onboarding experience.

I'd start with a Rollup version, but ultimately it could give you options for Rollup, webpack and whatever else

**Comment by Ryuno-Ki** [comment]
Hm, installing from the web requires a certain amount of trust. Do you plean to sign that .zip and display the computed hash (SHA3, GPG or something).

I want to be sure that nothing got changed while downloading.

**Comment by Rich-Harris** [comment]
It would be generated client-side, so there's no opportunity for someone to modify anything unless they somehow modified the site's JS, and I'm not sure how someone could do that given the site is served over HTTPS. It's like anything on the web — don't trust it, don't use it. Up to the user. I don't think it's any different to e.g. the 'export .zip' button on codepen.io (which gave me the idea).

**Comment by Ryuno-Ki** [comment]
You can generate a .zip client-side? O.o

**Comment by Rich-Harris** [comment]
https://stuk.github.io/jszip/

**Comment by Ryuno-Ki** [comment]
Hm, the mentioned browser versions are quite old, but [the project itself](https://github.com/Stuk/jszip) looks active.

**Comment by Rich-Harris** [comment]
Now implemented
