### ISSUE TITLE
`data=` REPL links from guide not working

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/svelte.technology#74]
The `data=` REPL links from examples embedded in the guide are not working currently. They're throwing an error about assigning to the undefined `source` variable (`({ source, components, data } = tryParseData( dataMatch[1] ));`) but there seems to be other stuff going on.

I'm looking into this, unless we're going to just remove support for those and handle embedded guide examples another way.

**Comment by Rich-Harris** [comment]
Ah, whoops 😬 

> unless we're going to just remove support for those and handle embedded guide examples another way

No, that's just something I broke!

**Comment by Rich-Harris** [comment]
Fixed in #76
