### ISSUE TITLE
REPL: `b` styles are overridden in Firefox

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/svelte.technology#77]
`<b>` elements in the REPL aren't appearing as bold in latest Firefox (I'm on Windows, if that matters), as seen in [this](https://svelte.technology/repl?data=JTdCJTIyZ2lzdCUyMiUzQW51bGwlMkMlMjJzb3VyY2UlMjIlM0ElMjIlM0NwJTNFVGhpcyUyMEhUTUwlM0ElMjAlN0IlN0JodG1sJTdEJTdEJTNDJTJGcCUzRSU1Q24lM0NwJTNFUmVuZGVycyUyMGFzJTNBJTIwJTdCJTdCJTdCaHRtbCU3RCU3RCU3RCUzQyUyRnAlM0UlNUNuJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMmh0bWwlMjIlM0ElMjJTb21lJTIwJTNDYiUzRWJvbGQlM0MlMkZiJTNFJTIwdGV4dC4lMjIlN0QlN0Q=) example linked to from the guide.

They look fine in Chrome, so I'm not sure whether this is a browser bug, or an expected difference we need to deal with. In Firefox, disabling the `p { font-weight: 300; }` rule makes the `<b>` elements appear as bold, but I don't know why that would have higher precedence than a `<b>` element inside the `<p>`.

**Comment by Rich-Harris** [comment]
Oh, Firefox. You never disappoint
