### ISSUE TITLE
App.html should be treated as entry component when loading from gist

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#82]
i.e., it shouldn't be possible to delete it (only clear it)

**Comment by Conduitry** [comment]
Ha I just came here to report this bug. It looks like we can rely solely on the filename for this.

Relatedly, the REPL should probably disallow multiple files with the same name. If you create another `App.html`, it looks like that one overrides the first one in the REPL. And later ones are going to override earlier ones when saving to a gist.

**Comment by Rich-Harris** [comment]
Both excellent points. We should also sort the files deterministically (probably App.html first, then alphabetical) since I'm not sure the order is in any way guaranteed

**Comment by Rich-Harris** [comment]
ha I missed you'd already PR'd this. nice, thanks 👍
