### ISSUE TITLE
audio video example is broken

### ISSUE THREAD

**Issue by ceremcem** [sveltejs/svelte.technology#88]
Here is the screenshot: 

![image](https://cloud.githubusercontent.com/assets/6639874/25222450/2716bcea-25c1-11e7-9b11-a57bc5e12a2e.png)

**Comment by Rich-Harris** [comment]
From that screenshot, it looks like you've got an old version of the REPL. Try a force refresh (Cmd-Shift-R)?

This is what happens when I try and do service workers...

**Comment by ceremcem** [comment]
I did nothing but opened the page as usual and worked OK: 

![image](https://cloud.githubusercontent.com/assets/6639874/25232455/068ff5fe-25e4-11e7-87ad-e77ac3ce327d.png)
