### ISSUE TITLE
REPL: Imports evaluated in container window context

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/svelte.technology#91]
From https://github.com/sveltejs/svelte/issues/535

See [this](https://svelte.technology/repl?version=1.18.1&gist=c4cf2e4cb367e469180e8ed01030adf0) example. This is importing a compiled Svelte component from npm. The imported component's style tags are being added to the outside document's head, presumably because the imports are being loaded with a curl-amd call from outside the iframe.

**Comment by therealnicksaunders** [comment]
You meant "style" tags, I think. :-) Thanks for creating the issue for me. :-)

**Comment by Conduitry** [comment]
The imports are being brought in [here](https://github.com/sveltejs/svelte.technology/blob/9d029eefc30de9e9f3f5ef11a803e14b6937a3de/shared/routes/Repl/Viewer.html#L83), using [curl](https://github.com/cujojs/curl). curl returns the already-evaluated module, in the context of the container window, so even when this module is passed into the iframe, its instances of `window` are still the outer window.
