### ISSUE TITLE
REPL: Need to avoid blowing away stylesheets of components imported via NPM

### ISSUE THREAD

**Issue by therealnicksaunders** [sveltejs/svelte.technology#93]
I found a new defect after fixing #91. After a component type is imported via npm/packd and initialized (stylesheet added to the document, etc.); when code is then changed in the editor, the viewer is reinitialized, which includes wiping out all the stylesheets. But now the imported component type is in the import cache and still thinks it's been initialized when in fact the stylesheet is gone.

Removing line 163 in shared/routes/Repl/Viewer.html could sorta fix it:
```
while ( i-- ) styles[i].parentNode.removeChild( styles[i] );
```

But you end up with a bunch of old stylesheets each time you make a code change.

Any other ideas?

**Comment by Conduitry** [comment]
@therealnicksaunders This is all set now that we have https://github.com/sveltejs/svelte/issues/554, correct?

**Comment by therealnicksaunders** [comment]
@Conduitry that is true. Thanks for your work on that!
