### ISSUE TITLE
Trouble running the site locally

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/svelte.technology#98]
Several weeks ago I started having trouble running the site locally. From a freshly ` git clone`d and `npm install`ed repo, if I run `npm run dev` I'm missing some CSS files. If I run `npm run bundle` and then `npm run dev` the CSS files are there, but edits don't seem to be getting watched properly.

A few times recently I've been in the mood for documenting some things but have been stymied by various technical problems. Not sure whether I'm doing something wrong or whether something else is broken. A very brief readme in this project describing the process would be nice.

**Comment by Rich-Harris** [comment]
Eek, sorry. I've added a README which hopefully clears everything up. In the medium term I'd like to make the build process a little bit less wonky as well
